### ISSUE TITLE
Java 1.6

### ISSUE THREAD

**Issue by jensleis** [watson-developer-cloud/java-sdk#174]
Are there any plans to get the lib compatible with Java 1.6, which is still more common on enterprise environments?
With the dependency to Java 1.7 it makes it nearly impossible at the moment to implement Watson services (in a simple way) for the most companies :(

**Comment by germanattanasio** [comment]
The library is being compiled and distributed using Java 1.6. See the [`pom.xml`](https://github.com/watson-developer-cloud/java-sdk/blob/master/pom.xml#L99)

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.2</version>
  <configuration>
    <source>1.6</source>
    <target>1.6</target>
  </configuration>
</plugin>
```

**Comment by jensleis** [comment]
Yes, this library. But due to the dependency to OkHttp it not usable with Java 1.6. (as also pointed out in the readme).
When I use the ‘with dependencies’-jar file, I’m getting a JVMCFRE003.
Hopefully I did something wrong :)

**Comment by germanattanasio** [comment]
You are right, I just found an [issue](https://github.com/square/okhttp/issues/528) where the problem was discussed. It looks like I will have to mention this in the README.md. 
Sadly I don't think we can find a solution here. `OkHttp` is being used as the underlying HTTP library.

Regarding your initial asumption that Java 1.6 is the common environment for enterprise. I did a quick Google search and found this [blog](https://plumbr.eu/blog/java/java-version-statistics-2015-edition), seems like **Java 1.6** is only in 20% of the existing JVMs. I don't know how accurate are those values. 

I'm going to try to find another library that work in 1.6

**Comment by jensleis** [comment]
Thanks. That would be great!

Regarding the statistics. It is not clear to me what they have count. It is looking to me that they didn't differentiated between client and server environments. Since even WebSphere Application Sever 7 (which is supporting Java 5) is still supported by IBM, I guess supporting at least Java 6 for this library would be a good compromise. ;)

**Comment by germanattanasio** [comment]
@jensleis what if we get the okhttp code, make it 1.6 compatible and build a `java-sdk-1.6-compatible-2.7.1.jar` ?

**Comment by jensleis** [comment]
For me that would be completely sufficient and helps me to implement against our customers environment.

**Comment by germanattanasio** [comment]
Hi @jensleis can you try with one of the two jars here: https://github.com/germanattanasio/okhttp/releases/tag/v2.3.0-java1.6

I forked the repo and build the jars

**Comment by jensleis** [comment]
Hey @germanattanasio, thanks for staying on that topic, but unfortunately not.

There is still a dependency to Java 1.7 within the okio-lib. But I took the sources from git and compiled it by myself with Java 1.6. (just one diamond-operator, hmpf)

After that, with the new jars provided by you, I ran into:
java.lang.NoClassDefFoundError: com.squareup.okhttp.HttpUrl
which isn't part of one of the packages. Did you forked the latest release of okhttp?

**Comment by germanattanasio** [comment]
I forked the 2.3.0 :( I think I need to fork 2.7.4

**Comment by briangleeson** [comment]
Was there ever a Java 6 compatible version of the Watson SDK finished?

**Comment by germanattanasio** [comment]
Nope, and I've updated the okhttp version to be 3.0.1.

**Comment by vinayreddy1983** [comment]
Hi,

Kindly point out the watson sdk jar that works for 1.6 java.  Unfortunately, we are not able to upgrade to java 1.8 because of our environment (1.8 doesn't work with notes plugins). From the discussion above, it appears that you had built 1.6 compatible sdk based on previous user's request? Please confirm.

**Comment by germanattanasio** [comment]
I didn't build it yet. I will try to do it next week

**Comment by ayushshah** [comment]
I tried to use simple Get Post requests to access the Watson Concept-Insights Service in Java6. However I could not get Post to work, probably because of a larger DH key being used. If you could please make the sdk available for 6 it will make things easier.

**Comment by germanattanasio** [comment]
I forked and updated `okhttp` and `okio` to be 1.6 compatible with JDK 1.6:
 * https://github.com/germanattanasio/okhttp/releases/tag/3.3.1.java16
 * https://github.com/germanattanasio/okio/releases/tag/1.10.0.java16

I use those dependencies to build the `java-sdk` and added it to the last release at the moment: https://github.com/watson-developer-cloud/java-sdk/releases/download/java-sdk-3.3.0/java-sdk-3.3.1.java16-jar-with-dependencies.jar

It works but if you want to use the Alchemy APIs you will have to disable SSL. Otherwise you will get something like:

```
Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLPeerUnverifiedException: Hostname gateway-a.watsonplatform.net not verified:
    certificate: sha256/zfDAdUtlCIKpDplDd0ng/vs8vv8GDQbhiL47DBQOSg0=
    DN: CN=access.alchemyapi.com, O="AlchemyAI, Inc.", L=Denver, ST=Colorado, C=US, SERIALNUMBER=5282053, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US
    subjectAltNames: [tickets.alchemyapi.com, access.alchemyapi.com]
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:181)
	at java16.AlchemyLanguageExample.main(AlchemyLanguageExample.java:36)
```

**Comment by luoyan011** [comment]
@germanattanasio , our environment also can not upgrade to Java 1.8 at this point. As such, I tried the 3.3.1 java1.6 compatible sdk and it works.  Thank you for posting this. 

I have a question here, do you plan to make all future releases after 3.3.1 (such as the latest 3.5.3) Java1.6-compatible?

**Comment by shiningbox** [comment]
Hi @germanattanasio , thank you for posting this release, it works in our project.

Can I ask a small question here, will all future release after 3.31 be Java 1.6 compatible?

Thanks again

**Comment by germanattanasio** [comment]
This is a manual process so I won't be doing releases for 1.6 very often

**Comment by djett41** [comment]
Im getting this error using Java 8 and AlchemyLanguage.  Unfortunately I cant upgrade to the new Language Understanding API yet.  I can hit the Translation endpoint using the java sdk, but get the same error when making requests to any alchemy language endpoint

```
javax.net.ssl.SSLPeerUnverifiedException: Hostname gateway-a.watsonplatform.net not verified:
    certificate: sha256/zfDAdUtlCIKpDplDd0ng/vs8vv8GDQbhiL47DBQOSg0=
    DN: CN=access.alchemyapi.com, O="AlchemyAI, Inc.", L=Denver, ST=Colorado, C=US, SERIALNUMBER=5282053, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US
    subjectAltNames: [tickets.alchemyapi.com, access.alchemyapi.com]
```

Is this a known issue or are there any suggestions @germanattanasio @g-may @jensleis ?  Thanks

**Comment by germanattanasio** [comment]
@djett41 That's a problem with the server. It will get fixed without you modifying your code.

**Comment by djett41** [comment]
Great thanks @germanattanasio !

**Comment by nrudd** [comment]
Thanks @germanattanasio for your comments and work on this issue.  Any chance of a JDK 1.6 version of the latest release?  Looks like 3.3.1 was the last version you made this manual build for?

**Comment by germanattanasio** [comment]
@nrudd This is a lot of work as I have to update the forked `okhttp` and `okio` to support 1.6
I have a lot of things on my plate if you can take the work of updating the two dependencies listed above I can update this library

**Comment by djett41** [comment]
@germanattanasio It seems that the server cert issue has resurfaced.  anyone aware of this?

**Comment by germanattanasio** [comment]
@lpatino10 can you look at 👆
