### ISSUE TITLE
java.lang.NoSuchMethodError with sdk 3.6.0

### ISSUE THREAD

**Issue by ugrani** [watson-developer-cloud/java-sdk#614]
The JVM throws `java.lang.NoSuchMethodError` when I upgrade my sdk from 3.5.3 to 3.6. Seems to be a dependency issue with okhttp/okio. 

```
Caused by: java.lang.NoSuchMethodError: okio/BufferedSource.rangeEquals(JLokio/ByteString;)Z (loaded from file:/opt/ibm/wlp/output/defaultServer/workarea/org.eclipse.osgi/79/data/cache/com.ibm.ws.app.manager_40/.cache/WEB-INF/lib/okio-1.6.0.jar by com.ibm.ws.classloading.internal.AppClassLoader@e9914ce0) called from class okhttp3.internal.Util (loaded from file:/opt/ibm/wlp/output/defaultServer/workarea/org.eclipse.osgi/79/data/cache/com.ibm.ws.app.manager_40/.cache/WEB-INF/lib/okhttp-3.6.0.jar by com.ibm.ws.classloading.internal.AppClassLoader@e9914ce0).
        at okhttp3.internal.Util.bomAwareCharset(Util.java:412)
        at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:248)
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1300)
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1346)
        at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1582)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.Gson.fromJson(Gson.java:806)
        at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:93)
        at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:79)
        at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)
        at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:405)
        at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:180)

```

**Comment by germanattanasio** [comment]
Can you provide code to reproduce the error?

**Comment by ugrani** [comment]
I used IBM JDK (IBM Bluemix Liberty docker container)

```
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3fp22-20161213_02(SR3 FP22))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20161209_329148 (JIT enabled, AOT enabled)
J9VM - R28_20161209_1345_B329148
JIT  - tr.r14.java.green_20161207_128946
GC   - R28_20161209_1345_B329148_CMPRSS
J9CL - 20161209_329148)
JCL - 20161213_01 based on Oracle jdk8u111-b14
```
The code is similar to what is mentioned here in the sample below(Java example)
https://www.ibm.com/watson/developercloud/conversation/api/v1/#send_message

**Comment by germanattanasio** [comment]
I think that this is related to #610

**Comment by germanattanasio** [comment]
@ugrani can you try again using 3.7.1 ?

**Comment by JoshSharpe** [comment]
I am using the same project as @ugrani. Using 3.7.2 version of conversation sdk. Tried 3.7.0 and 3.7.1. Still getting the following error ```javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: okio/BufferedSource.rangeEquals(JLokio/ByteString;)Z (loaded from file:/opt/ibm/wlp/output/defaultServer/workarea/org.eclipse.osgi/80/data/cache/com.ibm.ws.app.manager_40/.cache/WEB-INF/lib/okio-1.6.0.jar by com.ibm.ws.classloading.internal.AppClassLoader@9b347f45) called from class okhttp3.internal.Util (loaded from file:/opt/ibm/wlp/output/defaultServer/workarea/org.eclipse.osgi/80/data/cache/com.ibm.ws.app.manager_40/.cache/WEB-INF/lib/okhttp-3.6.0.jar by com.ibm.ws.classloading.internal.AppClassLoader@9b347f45).
```

Recently downloaded the latest ibmliberty image for bluemix containers.

**Comment by danwig52** [comment]
@germanattanasio This is starting to be urgent for us, how do we proceed?

**Comment by germanattanasio** [comment]
I'm going to look at it tomorrow. I'm out of office today

**Comment by JoshSharpe** [comment]
Moving back to an old IBM Liberty image worked in resolving the issue by allowing me to move back to 3.6.3 sdk.

**Comment by jagan120** [comment]
@germanattanasio I work with @JoshSharpe and @ugrani. We are seeing this error consistently with new SDK Versions(3.7+). Doesnt matter if I use new/old Liberty. The Workaround we are using for now is not updating the SDK Version and using older liberty. Newer Liberty gives cipher issues with older versions of SDK.

cc : @danwig52

**Comment by germanattanasio** [comment]
I've updated the okhttp version to 3.7.0 which includes a new version of okio.
Before I do a release I want to make sure this change will fix your problem.

Can you guys download the SNAPSHOT from sonatype. It should be `3.7.3-SNAPSHOT`

**Comment by jagan120** [comment]
We have a different problem now. This is the stacktrace I see when connecting to conversation :

```
java.lang.RuntimeException: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_3, TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true), ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_0], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1, TLSv1.1, TLSv1.2]
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:185) ~[core-3.7.3-20170419.213629-2.jar:?]
	at com.ibm.watson.bots.conversation.client.ConversationClient.callVoyager(ConversationClient.java:193) [watson-bot-sdk-0.1.jar:?]
	at com.ibm.watson.bots.conversation.client.ConversationClient.rawMessageVoyager(ConversationClient.java:158) [watson-bot-sdk-0.1.jar:?]
	at com.ibm.watson.bots.conversation.client.ConversationClient.messageVoyager(ConversationClient.java:76) [watson-bot-sdk-0.1.jar:?]
	at com.ibm.watson.bots.wft.conversation.BotConversationClient.invokeDialogVoyager(BotConversationClient.java:69) [wva.war:?]
	at com.ibm.watson.wva.bots.aggregator.IntentAggregator.handleDialog(IntentAggregator.java:109) [wva.war:?]
	at com.ibm.watson.wva.bots.aggregator.IntentAggregator.processDialog(IntentAggregator.java:54) [wva.war:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95) ~[?:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.23.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.23.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.23.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.23.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.23.2.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.23.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.23.2.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) [jersey-container-servlet-core-2.23.2.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) [jersey-container-servlet-core-2.23.2.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) [jersey-container-servlet-core-2.23.2.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) [jersey-container-servlet-core-2.23.2.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) [jersey-container-servlet-core-2.23.2.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1290) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:778) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:475) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:152) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.watson.wva.bots.init.HttpHeaderInterceptor.doFilter(HttpHeaderInterceptor.java:50) [wva.war:?]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.watson.bots.init.BasicAuthFilter.doFilter(BasicAuthFilter.java:67) [watson-bot-sdk-0.1.jar:?]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.watson.bots.init.LogTagFilter.doFilter(LogTagFilter.java:55) [watson-bot-sdk-0.1.jar:?]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.6.2.jar:2.6.2]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1021) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1143) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:945) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:280) [com.ibm.ws.webcontainer_1.1.16.jar:?]
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:967) [com.ibm.ws.transport.http_1.0.16.jar:?]
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:359) [com.ibm.ws.transport.http_1.0.16.jar:?]
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:318) [com.ibm.ws.transport.http_1.0.16.jar:?]
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:471) [com.ibm.ws.transport.http_1.0.16.jar:?]
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:405) [com.ibm.ws.transport.http_1.0.16.jar:?]
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:285) [com.ibm.ws.transport.http_1.0.16.jar:?]
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:256) [com.ibm.ws.transport.http_1.0.16.jar:?]
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1043) [com.ibm.ws.channel.ssl_1.0.16.jar:?]
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInboundPostHandshake(SSLConnectionLink.java:709) [com.ibm.ws.channel.ssl_1.0.16.jar:?]
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyHandshakeCompletedCallback.complete(SSLConnectionLink.java:397) [com.ibm.ws.channel.ssl_1.0.16.jar:?]
	at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:976) [com.ibm.ws.channel.ssl_1.0.16.jar:?]
	at com.ibm.ws.channel.ssl.internal.SSLHandshakeIOCallback.complete(SSLHandshakeIOCallback.java:88) [com.ibm.ws.channel.ssl_1.0.16.jar:?]
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504) [com.ibm.ws.channelfw_1.0.16.jar:?]
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574) [com.ibm.ws.channelfw_1.0.16.jar:?]
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929) [com.ibm.ws.channelfw_1.0.16.jar:?]
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018) [com.ibm.ws.channelfw_1.0.16.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153) [?:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:1.8.0]
	at java.lang.Thread.run(Thread.java:785) [?:?]
Caused by: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_3, TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true), ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_0], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1, TLSv1.1, TLSv1.2]
	at okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:73) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:260) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.6.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.6.0.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) ~[okhttp-3.6.0.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:63) ~[okhttp-3.6.0.jar:?]
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:182) ~[core-3.7.3-20170419.213629-2.jar:?]
	... 73 more
```

**Comment by germanattanasio** [comment]
Fixed
